### ISSUE TITLE
Comparative experiments on PI directly on 2k length

### ISSUE THREAD

**Issue by wutong4012** [dwzhu-pku/PoSE#10]
hi, @dwzhu-pku , have you ever tried performing PI directly on a length of 2k, and then compared using PoSE to perform PI on a length of 2k? Also fine-tune 1000 steps with the same parameters.

My results show that there is not much difference between the two, but I did not find any relevant comparative experiments in the paper.

Please correct me if I'm wrong.

**Comment by dwzhu-pku** [comment]
hi @victor! Take context extension from 2k to 16k as an example, If I understand correctly, the two settings you mentioned are:

- use 2k training context, keep the original pids {0,1,...,2047}, use PI to downscale the pids by 8 times into {0,1/8,...,2047/8}, then train for 1k steps.
- use 2k training context, use pose to adjust pids, for example {0,1,...,511, 6560,6561,...,8095}, use PI to downscale the pids by 8 times, then train for 1k steps.

I have not tested the first setting, and I'm very curious about in what sense can the first setting achieve similar performance with the second one. Can you provide more details on the evaluation settings you are using?

**Comment by wutong4012** [comment]
Thanks for your reply, your setup is exactly what I thought it would be.

I tested PPL on GovReport and Proof-pile, whether Linear or Yarn, and fine-tuned it on 2k {0,1,2,...,2046,2047}. PPL was not very large at 16K. Of course, there is no doubt that if switch to PoSE, the effect will be better.

To this end, I specifically took a look at the approach of "SCALING LAWS OF ROPE-BASED EXTRAPOLATION". What they wrote in their paper is also about fine-tuning the context length.

![image](https://github.com/dwzhu-pku/PoSE/assets/41939510/dd67a879-cd18-4518-b00f-4c55c9e8f85a)
![image](https://github.com/dwzhu-pku/PoSE/assets/41939510/04c378ad-da7b-437f-b7e3-51537c9d1c48)

**Comment by dwzhu-pku** [comment]
Bravo! You reply also reminds me of this paper "Effective Long-Context Scaling of Foundation Models", where they show that  continual pretraining with rope_theta adjusted from 10,000 to 500,000 can enhance length extrapolation. Personally I think it's also a very good strategy. Perhaps PoSE is slightly more efficient and delivers better performance?

**Comment by dwzhu-pku** [comment]
and how about passkey retrieval results for these two settings?

**Comment by wutong4012** [comment]
According to my current experiments (if there are no bugs), the training time is almost the same, and the passkey retrieval results are also similar. However, PoSE is slightly better.

My guess is that PI fine-tuning directly on the context length seems to learn a small spacing? In this way, when the length is extended to 16K, and then PI is increased to 2K, the spacing has been learned during fine-tuning, so the effect will not be bad.

PoSE learns the length extension under the original pre-training spacing, and uses the difference in relative positions to learn all relative pids from 0 to 16K. Therefore, it learns more fully and is closer to the pre-training, so the effect will be slightly better?

**Comment by dwzhu-pku** [comment]
thanks a lot for this insightful explanation!

**Comment by victor** [comment]
please be careful with your @-mentions

> hi @victor! Take context extension from 2k to 16k as an example, If I understand correctly, the two settings you mentioned are:
> 
> * use 2k training context, keep the original pids {0,1,...,2047}, use PI to downscale the pids by 8 times into {0,1/8,...,2047/8}, then train for 1k steps.
> * use 2k training context, use pose to adjust pids, for example {0,1,...,511, 6560,6561,...,8095}, use PI to downscale the pids by 8 times, then train for 1k steps.
> 
> I have not tested the first setting, and I'm very curious about in what sense can the first setting achieve similar performance with the second one. Can you provide more details on the evaluation settings you are using?

**Comment by dwzhu-pku** [comment]
thanks bro
