### ISSUE TITLE
“input_ids” is the same as "labels" in train_preprocess_function_pose function ?

### ISSUE THREAD

**Issue by Jianwei-Lv** [dwzhu-pku/PoSE#11]
“input_ids” is the same as "labels" in train_preprocess_function_pose function ?
model_inputs = {"input_ids": input_ids, "position_ids": position_ids, "labels": input_ids}

**Comment by Jianwei-Lv** [comment]
函数train_preprocess_function_pose function 中的 “input_ids” 和 "labels" 是一样，但是我理解labels应该跟input_ids不一样，错位一个。

**Comment by dwzhu-pku** [comment]
hi @Jianwei-Lv , 感谢你的关注！huggingface的代码里面一般是在forward的时候对label进行shift，参见 https://github.com/dwzhu-pku/PoSE/blob/master/src/my_modeling_llama.py#L994
