### ISSUE TITLE
能支持LLaMA3的上下文扩展吗

### ISSUE THREAD

**Issue by zhilingz** [dwzhu-pku/PoSE#14]
能支持LLaMA3的上下文扩展吗，效果怎么样

**Comment by dwzhu-pku** [comment]
你好@zhilingz，感谢您的关注！我们没有在LLaMA3进行实验，不过根据我们在LLaMA、LLaMA2、Baichuan等模型上的实验结果，PoSE应该也能用于LLaMA3的上下文拓展。至于性能，则还受到用来fine-tune的语料本身的影响。我们相信，在保证data engineering质量（如 Data Engineering for Scaling Language Models to 128K Context 这篇paper所讨论的）的前提下，PoSE能高效地拓展context window，并且保持模型的基础能力不受影响。

**Comment by zhilingz** [comment]
非常感谢！
