### ISSUE TITLE
代码支持中文数据集训练吗

### ISSUE THREAD

**Issue by jy-101361-1810897** [dwzhu-pku/PoSE#17]
将训练数据集替换成中文的，代码需要修改吗

**Comment by dwzhu-pku** [comment]
@jy-101361-1810897 您好，感谢关注！我们的训练过程仅仅调整了训练数据的position id，所以把数据集替换成中文，应该不需要做什么修改，只需要换上对应的中文模型和tokenizer即可 :-)

**Comment by jy-101361-1810897** [comment]
好的，感谢回复
