### ISSUE TITLE
Example Training data

### ISSUE THREAD

**Issue by horvay** [dwzhu-pku/PoSE#2]
Hi, this seems like an amazing breakthrough to me, and I'm not sure how it isn't getting more attention.

Anyway, I was looking at your docs and particular your scripts. Do you all have links to the training/testing jsonl files you used? I wanted to look at it to get an idea of what to pass in.

**Comment by dwzhu-pku** [comment]
Hi @horvay, thanks a lot for your attention! I simply don't know how to earn this work more attention, very glad to hear any advice :-). 
As for the dataset, I have released it here: https://huggingface.co/datasets/dwzhu/PoSE-Datasets/tree/main. Hope they may help!

**Comment by horvay** [comment]
Frankly, I don't either. I am currently looking into the ability to use Llama to upgrade old dotnet code to a newer version. The problem is that most repos are over 4k tokens. I'm hoping to use the PoSE technology to extend the context of a specialized dotnet llama2 model.
