### ISSUE TITLE
建议把数据上传到国内的魔塔社区一份

### ISSUE THREAD

**Issue by sunshineflg** [dwzhu-pku/PoSE#3]
建议把数据上传到国内的魔塔社区一份

**Comment by dwzhu-pku** [comment]
感谢关注！我们会尽快上传 :-)

**Comment by sunshineflg** [comment]
脚本训练的模型是baichuan base模型，chat能力较弱吧？

**Comment by dwzhu-pku** [comment]
是的。主要是为了验证一下PoSE这个做法在多种大模型上有效，所以就只选用了Base版本。Chat版本应该也可以通过相同的训练方式实现窗口扩展。@sunshineflg
