### ISSUE TITLE
A question about data preproecess

### ISSUE THREAD

**Issue by cizhenshi** [dwzhu-pku/PoSE#6]
https://github.com/dwzhu-pku/PoSE/blob/e0eb5c75e1f7706650ff71a4b66a61c0bb48e8b0/src/train_pose.py#L172

Hi，in line 172 of the file, it appears that two non-adjacent fragments have been cut from the original training data, and each of these fragments has been assigned a continuous positional code in subsequent processing. Why is this done? 
In a real SFT scenario, the raw data input is often continuous fragments. What is the problem with using continuous fragments and applying pose?

**Comment by dwzhu-pku** [comment]
Hello @cizhenshi, thank you for your interest in our work!

The reason for this design is that at the beginning, we thought that if the position encoding between two chunks is not continuous, then it would be best if their content is also not continuous. However, we conducted experiments in Appendix A and found that whether the text content between two chunks is continuous or not does not have a significant impact.

I completely agree with your point that in the SFT scenario, the content between two chunks can also be kept continuous, with only the position encoding being changed. This way, no key information will be lost, and the code implementation will even be easier. Although I have not tested the effectiveness of PoSE in the SFT scenario, I am confident that it would perform well. 🙂
